language: node_js
node_js:
- stable
script:
- npm run test
- npm run build
notifications:
  slack:
    secure: KvDq8NC/oCLOhGlvSHQ6yIpuSdAWudvoeqDR4CxsWULCTxzMax33mycZit5zdzbuUHxAg1NWjcKJov8CpAt/TWh8LPrvU/w9zyuNWmF7c4b776R438o7RmWUVUY0YLwkRiIxpSfYAhOkaIKyS/50u8UqXLxfKNCkIDC7XALDnzZDmUXybPE0pRTJgOdBM9CKHMpHImaqVDNCDRBoop3jYIeC/3spUx+w3ImUVYVBjBUiaKQteZJkjaz46WOzNjpivWZo7t15hnT6+eTlU8MSyenI8gEs1XgZScMk54aN7QkBNeDlatqt10l6/8jeofiogpj5qd1HNclg/HKZIg3b7+SdBIcRKuxFr3Rq7nHqV0D3WKVUcTdbS+kJx/tRY0FzxuKRewcPaVBKwkYBp7+77C+d8eWR6cII5hbaeNwnll4+fgTNfrvwzzO+oWGLPiBp5K1sMzvS12rw61TxYIUOFaDC0qOo/+oqNPvGQ6FdfHMFrXDxfKfVvdxIvoMHJgsF73iRHxzZnGtPY86tVyeuKYKhJWcFoZy80VGQmTywiX1X7/nExY/E8JchoD7WNqmSFKQz+/PQ1xe51hf8YKW+UZbvTAmxALUfJLnN0Qiy6V8iPoGssnook+WuvxD4bX8DRBXK2imUpbjxHio/Z30pwXgJ+AgQdj6E1YRpg6yx1d4=
